name: Test Java SDK library

on:
  push:
    branches: [ master, beta ]
  pull_request:
    branches: [ master, beta ]
    types: [ opened, reopened, synchronize ]
    
jobs:
  test:
    name: Test java project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
      - name: Setup Gradle 8.10
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.6"
      - name: Run local-setup
        run: |
          git clone https://github.com/matter-labs/local-setup.git
          pushd local-setup
          ./start.sh
          popd
      - name: Test with Gradle
        run: gradle clean test
