name: Test Java SDK library

on:
  workflow_dispatch:
  push:
    branches: [ master, beta ]
  pull_request:
    branches: [ master, beta ]
    types: [ opened, reopened, synchronize ]
    
jobs:
  test:
    name: Test java project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.11
      - name: Run local-setup
        run: |
          git clone https://github.com/matter-labs/local-setup.git
          pushd local-setup
          ./start-zk-chains.sh
          popd
      - name: Print Gradle Version from Wrapper
        run: ./gradlew --version
      - name: Test with Gradle
        run: gradle clean test
